# This file has been generated -- see https://github.com/phadej/travis-meta-yaml
sudo: false
language: c
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- if [ -n "$CABALVER" ]; then export PATH=/opt/cabal/$CABALVER/bin:$PATH; fi
- export PATH=~/.local/bin:$PATH
- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L
  https://github.com/commercialhaskell/stack/releases/download/v1.0.2/stack-1.0.2-linux-x86_64.tar.gz
  | tar --strip-components=1 -xz -C ~/.local/bin stack-1.0.2-linux-x86_64/stack; fi
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- stack +RTS -N2 -RTS --version
install:
- if [ "$STACK_SOLVER" = "YES" ]; then rm -f stack.yaml; stack update; stack init
  --solver; fi; stack --no-terminal --skip-ghc-check list-dependencies|sort > installplan.txt;
  cat installplan.txt; stack --no-terminal --skip-ghc-check setup; if diff -u $HOME/.stack-work-cache/installplan.txt
  installplan.txt; then echo "cabal build-cache HIT"; rm -rf .stack-work; cp -a $HOME/.stack-work-cache
  .stack-work; rm -f .stack-work/installplan.txt; else echo "cabal build-cache MISS";
  rm -rf $HOME/.stack-work-cache; stack --no-terminal --skip-ghc-check build --test
  --only-dependencies; fi; if [ ! -d $HOME/.stack-work-cache ]; then echo "snapshotting
  package-db to build-cache"; cp -a .stack-work $HOME/.stack-work-cache; cp -a installplan.txt
  $HOME/.stack-work-cache/installplan.txt; fi;
- hash -r
before_script:
- wget 'https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip'
- unzip "consul_0.6.3_linux_amd64.zip"
script:
- ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
- stack --no-terminal --skip-ghc-check build --test
- stack --no-terminal --skip-ghc-check sdist
matrix:
  fast_finish: true
  include:
  - env: GHCVER=7.10.3 CABALVER=1.22 STACK_SOLVER=NO
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
        - cabal-install-1.22
        - libgmp-dev
    compiler: ! ': # ghc-7.10.3  NO'
  - env: GHCVER=head CABALVER=1.22 STACK_SOLVER=YES
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-head
        - cabal-install-1.22
        - libgmp-dev
    compiler: ! ': # ghc-head  YES'
  allow_failures:
  - env: GHCVER=head CABALVER=1.22 STACK_SOLVER=YES
branches:
  only:
  - master
cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.stack-work-cache
  apt: true
